# -*- coding: utf-8 -*-
"""Ejercicio17Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZYy_K-WBruA7ly1RWODz_EBNDj5no0Sg

**Escribir programa que genere y muestre por pantalla un DataFrame con los datos de la tabla siguiente:**
http://fesat.mendoza.edu.ar:8080/pluginfile.php/15033/mod_assign/intro/image.png
"""

import pandas as pd
import numpy as np

# Vamos a crear DataFrame con diccionario de listas, donde mes, ventas y gastos seran las claves y, los datos de cada una los valores

dic = {'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril'],
       'Ventas': ['30500', '35600', '28300', '33900'],
       'Gastos': ['22000', '23400', '18100', '20700']}

df = pd.DataFrame(dic, index = ['a','b','c','d'])

df