
# Crear una variable que contenga el texto que ustedes quieran en formato byte , en lo posible extenso, y convertirlo a Unicode.

# Primero voy a tomar un texto de interés y a convertirlo a byte, ya que no leemos en bytes y la consigna pide que tome un texto en bytes y lo convierta a unicode. Para ello uso .encode()

txt = 'El preludio es uno de los géneros más singulares del periodo barroco. Concebido como pieza introductoria a una obra más extensa y compleja (p.e. una fuga) o a una suite de danzas, las características musicales del preludio remiten a dos funciones básicas que todo instrumentista ha ejercitado: tantear la afinación o las cualidades sonoras del instrumento (especialmente si es la primera vez que se toca) y «calentar» los dedos antes de acometer la interpretación de una obra exigente. En esta primera entrada dedicada al preludio estudiaremos uno de los más famosos de la era barroca, el que abre la primera Suite para violonchelo solo BWV 1007, en Sol mayor, de J. S. Bach. Un aficionado al cello de la familia Van der Mersch [1736], óleo de Cornelis Troost.Como hemos adelantado en la introducción, el acto de preludiar es una acción inseparable del oficio del instrumentista. Esta acción suele ser llevada a cabo mediante el encadenamiento libre de elementos variopintos, como escalas, arpegios, pasajes de diversas obras o fragmentos improvisados. Esta actividad, en principio puramente mecánica, pero de gran importancia desde el punto de vista de la preparación física y psíquica del intérprete, ha alcanzado en determinados contextos una cierta categoría artística, desembocando eventualmente en la escritura de obras -por lo general de pequeña extensión- que nos permiten hoy en día hacernos una ligera idea del sofisticado arte improvisatorio de otras épocas. Fue Louis Couperin -tío del más famoso de los Couperin, François– quien instituyó a mediados del siglo XVII un influyente modelo de este género, gracias a los préludes non mesurés (preludios en ritmo libre) que incluyó en sus suites para clave. El origen improvisatorio de estas piezas queda reflejado de forma elocuente en su renuncia al compás y al empleo de un sistema de notación rítmica que deja al intérprete una libertad total en cuanto a la elección de las duraciones de las notas. En cuanto a Bach -un improvisador excepcional, según los testimonios de la época-, desarrolló este género a partir de modelos que contaban con una notable raigambre en Alemania, y que habían sido practicados -o lo siguieron siendo- por grandes maestros organistas -como Dietrich Buxtehude o Johann Pachelbel– o laudistas, como su amigo Sylvius Leopold Weiss, cuyas suites instrumentales guardan notables semejanzas con las del compositor de Leipzig.'

print(txt.encode())

print( )

# Una vez impreso, lo copio tal cual desde la terminal y ahora lo convierto a unicode, para ello creo una variable y utilizo el método .decode()

byte = b'El preludio es uno de los g\xc3\xa9neros m\xc3\xa1s singulares del periodo barroco. Concebido como pieza introductoria a una obra m\xc3\xa1s extensa y compleja (p.e. una fuga) o a una suite de danzas, las caracter\xc3\xadsticas musicales del preludio remiten a dos funciones b\xc3\xa1sicas que todo instrumentista ha ejercitado: tantear la afinaci\xc3\xb3n o las cualidades sonoras del instrumento (especialmente si es la primera vez que se toca) y \xc2\xabcalentar\xc2\xbb los dedos antes de acometer la interpretaci\xc3\xb3n de una obra exigente. En esta primera entrada dedicada al preludio estudiaremos uno de los m\xc3\xa1s famosos de la era barroca, el que abre la primera Suite para violonchelo solo BWV 1007, en Sol mayor, de J. S. Bach. Un aficionado al cello de la familia Van der Mersch [1736], \xc3\xb3leo de Cornelis Troost.Como hemos adelantado en la introducci\xc3\xb3n, el acto de preludiar es una acci\xc3\xb3n inseparable del oficio del instrumentista. Esta acci\xc3\xb3n suele ser llevada a cabo mediante el encadenamiento libre de elementos variopintos, como escalas, arpegios, pasajes de diversas obras o fragmentos improvisados. Esta actividad, en principio puramente mec\xc3\xa1nica, pero de gran importancia desde el punto de vista de la preparaci\xc3\xb3n f\xc3\xadsica y ps\xc3\xadquica del int\xc3\xa9rprete, ha alcanzado en determinados contextos una cierta categor\xc3\xada art\xc3\xadstica, desembocando eventualmente en la escritura de obras -por lo general de peque\xc3\xb1a extensi\xc3\xb3n- que nos permiten hoy en d\xc3\xada hacernos una ligera idea del sofisticado arte improvisatorio de otras \xc3\xa9pocas. Fue Louis Couperin -t\xc3\xado del m\xc3\xa1s famoso de los Couperin, Fran\xc3\xa7ois\xe2\x80\x93 quien instituy\xc3\xb3 a mediados del siglo XVII un influyente modelo de este g\xc3\xa9nero, gracias a los pr\xc3\xa9ludes non mesur\xc3\xa9s (preludios en ritmo libre) que incluy\xc3\xb3 en sus suites para clave. El origen improvisatorio de estas piezas queda reflejado de forma elocuente en su renuncia al comp\xc3\xa1s y al empleo de un sistema de notaci\xc3\xb3n r\xc3\xadtmica que deja al int\xc3\xa9rprete una libertad total en cuanto a la elecci\xc3\xb3n de las duraciones de las notas. En cuanto a Bach -un improvisador excepcional, seg\xc3\xban los testimonios de la \xc3\xa9poca-, desarroll\xc3\xb3 este g\xc3\xa9nero a partir de modelos que contaban con una notable raigambre en Alemania, y que hab\xc3\xadan sido practicados -o lo siguieron siendo- por grandes maestros organistas -como Dietrich Buxtehude o Johann Pachelbel\xe2\x80\x93 o laudistas, como su amigo Sylvius Leopold Weiss, cuyas suites instrumentales guardan notables semejanzas con las del compositor de Leipzig.'

print(byte.decode()) 


